import {StyleSheet} from 'react-native';

export const mainStyles = StyleSheet.create({
    screen: {
    flex: 1,
    paddingBottom: 100,
    backgroundColor: '#F7F9FB',
  },
  topButtonContainer: {
    marginTop: 40,
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  headingContainer: {
    marginTop: 20,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  heading: {
    fontSize: 15,
    fontWeight: 'bold',
    textAlign: 'center',
    backgroundColor: 'skyblue',
    padding: 10,
  },
  bottomButtonContainer: {
    marginTop: 20,
    width: '30%',
    alignSelf: 'center',
  },
  buttonStyle: {
    width: '35%',
  },
  listStyle: {
    marginTop: 20,
  },
  listItem: {
    width: '90%',
    borderWidth: 1,
    borderRadius: 10,
    alignSelf: 'center',
    padding: 5,
    marginBottom: 10,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    backgroundColor: 'white',
  },
  setButton: {
    width: '21%',
    margin: 2,
  },
  listExercise: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  exerciseName: {
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 2,
  },
  setListItem: {
    width: '90%',
    height: 50,
    borderWidth: 0.75,
    borderRadius: 10,
    backgroundColor: '#D9F4F2',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    alignSelf: 'center',
    paddingLeft: 5,
    marginTop: 5,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  setNumber: {
    fontWeight: 'bold',
    textShadowColor: 'rgba(0, 0, 0, 0.25)',
    textShadowOffset: {width: 0, height: 1},
    textShadowRadius: 2,
  },
  setInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  input: {
    width: 40,
    height: 40,
    textAlign: 'center',
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 5,
    backgroundColor: 'white',
    color: 'black',
  },
  deleteButton: {
    padding: 4,
    backgroundColor: '#FF6B6B',
    alignSelf: 'center',
    borderRadius: 5,
  },
});